build:
	gcc reset_env.c -o reset-env01
	chown root:env01 reset-env01
	chmod 2750 reset-env01
	gcc reset_env.c -o reset-env02
	chown root:env02 reset-env02
	chmod 2750 reset-env02
	gcc reset_env.c -o reset-env03
	chown root:env03 reset-env03
	chmod 2750 reset-env03
	gcc reset_env.c -o reset-env04
	chown root:env04 reset-env04
	chmod 2750 reset-env04
